version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-buster-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6d:39:4f:12:b8:1a:89:0c:18:60:9d:26:f8:77:13:c7"
      - checkout

      - run:
          name: Prepare Release
          command: bash prepare-release.sh

      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - run:
          name: Unit Test
          command: npm run test:unit
          working_directory: client


      - run:
          name: Build
          command: npm run build
          working_directory: client

      - run:
          name: Release
          command: npm run version

workflows:
  build:
    jobs:
      - build
