version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-buster-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "95:c6:ea:61:74:37:85:47:d3:e3:4f:15:87:5e:3f:74"

      - checkout

      - run:
          name: Prepare Release
          command: bash prepare-release.sh

      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - run:
          name: Unit Test
          command: npm run test:unit
          working_directory: client


      - run:
          name: Build
          command: npm run build
          working_directory: client

      - run:
          name: Release
          command: bash release.sh

      - run:
          name: Test
          command: echo "test"

workflows:
  build:
    jobs:
      - build
