version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12-buster-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:d5:24:23:f5:59:e7:c3:d2:35:02:ae:2c:80:f1:1a"
            -
      - checkout

      - run:
          name: Prepare Release
          command: bash prepare-release.sh

      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - run:
          name: Unit Test
          command: npm run test:unit
          working_directory: client


      - run:
          name: Build
          command: npm run build
          working_directory: client

      - run:
          name: Release
          command: bash release.sh

workflows:
  build:
    jobs:
      - build
